### ISSUE TITLE
Unknown property with value "left" or "right" should not be flipped

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/mediawiki-libs-node-cssjanus#24]
Input:

``` css
.foo {
    unknown: left;
}
```

Output should be unchanged, but isn't:

``` css
.foo {
    unknown: right;
}
```
